yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path
from . import views
# имя пространста имен
app_name = 'posts'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('group/<slug:slug>/', views.group_posts, name= 'group_list'),
    path('profile/<str:username>/', views.profile, name= 'profile'),
    path('post_detail/<int:post_id>/', views.post_detail, name= 'post_detail'),
    path('create/', views.post_create, name= 'post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='update_post'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),    
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, 
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Пользовательские приложения
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('users/', include('users.urls', namespace='users')),
    #Стандартные приложения
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

# Данная запись позволяет обращаться 
# к файлам в дерриктории при режиме отладки указанной в 
# в MEDIA_ROOT по имени, через префикс MEDIA_URL
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model() #Модель отвечающая за управление пользователями

class Post(models.Model):
    
    text = models.TextField() # поле формата текст
    pub_date = models.DateTimeField(auto_now_add= True) # поле даты создания поста. auth_now_add-для автоматическогоприсваения даты посту
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name='posts'
        ) # полея для указания ссылки на другую модель(другую таблицу) 
    #on_delete=models.CASCADE обеспечивает связанность данных при удаление пользователя будут удалены все посты 
    group = models.ForeignKey(
        'Group',
        blank= True,
        null= True,
        on_delete = models.SET_NULL,
        related_name = 'groups'                
    )
    # Поле для картинки  (не обязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/', # Дирректория куда будут загружаться файлы
        blank=True
    )


    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        # выводим текст поста 
        return self.text[0:15]

class Group(models.Model):
    
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()    

    def __str__(self):        
        return self.title[0:10] # в имени группы выведет первые 10 символов

class Comment(models.Model):

    post = models.ForeignKey(
        'Post',
        null= True,
        on_delete = models.CASCADE,
        related_name = 'comments'                
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
        )
    text = models.TextField() # поле формата текст
    created = models.DateTimeField(auto_now_add= True)

class Follow(models.Model):
    """ Модель системы подписки """
    # Кто подписан
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    # На кого подписан
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        # модель с которой будет связана создаваемая форма
        model = Post
        # укажем какие полня должны быть видны в форме и в каком порядке
        fields = ('text','group', 'image')

class CommentForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Comment, Follow
from .utils import My_paginator, Source_author, Source_posts
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from django.views.decorators.cache import cache_page


NUM_OF_POSTS = 10 # количество постов для вывода на страницу

#функция обработки главной страницы
@cache_page(20 * 2)
def index(request):
    template = 'posts/index.html'
    #posts = Post.objects.select_related('author', 'group')[:NUM_OF_POSTS] # последние количество постов из базы данных
    #Запрос к базе данных 
    post_list = Post.objects.all()
    #Создание погинатора с параметрами по 10 на странице
    page_obj = My_paginator(request, post_list, NUM_OF_POSTS) # вынесли пагинатор в отдельный файл
    context = {        
        'page_obj': page_obj
    }
    return render(request, template, context)

# функция обработки групп
def group_posts(request, slug):  
    template = 'posts/group_list.html'    
    group = get_object_or_404(Group, slug=slug)
    #posts = Post.objects.filter(group=group).order_by('-pub_date')[:NUM_OF_POSTS]
    post_list= group.groups.all()# group-object, groups-related name models, all()- all posts group
    page_obj = My_paginator(request, post_list, NUM_OF_POSTS)
    context = {        
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)

def profile(request, username):
    # Код запроса к модели и создание словоря контекста  
    
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    amount_posts = post_list.count() # amount posts user
    
    all_following = Follow.objects.filter(user_id=request.user.pk) # все follow на котрых подписан пользователь
    following = Source_author(all_following, username) # самописная функция 
    """
    paginator = Paginator(post_list, NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    """
    page_obj = My_paginator(request, post_list, NUM_OF_POSTS) # вынесли пагинатор в отдельный файл
    context = {
        'user': user,
        'page_obj': page_obj,
        'amount_posts': amount_posts,
        'following': following,
    }
    return render(request, template , context)
    

def post_detail(request, post_id):
    # код запроса инофрмации о конкретном посте


    template = 'posts/post_detail.html'
    post = Post.objects.get(pk=post_id)    
    amount_posts_author = post.author.posts.all().count()
    comments = post.comments.all() # Комментарий относящийся к определенному посту
    form = form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'amount_posts_author': amount_posts_author,
        'comments': comments,
        'form': form
    }
    return render(request, template , context)

@login_required 
def post_create(request): 
    form = PostForm(request.POST or None, files=request.FILES or None) 
    if not request.method == 'POST':
        return render( 
            request, 
            'posts/create_post.html', 
            {'form': form}
        ) 
    
    if not form.is_valid(): 
        return render( 
            request, 
            'posts/create_post.html', 
            {'form': form} 
        ) 
    post = form.save(commit=False) 
    post.author = request.user 
    post.save() 
    return redirect('posts:profile', request.user.username) 
    
 
@login_required 
def post_edit(request, post_id): 
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    ) 
    if request.method == 'POST': 
        if form.is_valid():
            form.save() 
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render( 
        request, 
        'posts/create_post.html', 
        context 
    )

@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    else:
        messages.error(request,'Error')    
    return redirect('posts:post_detail', post_id=post_id)

@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    #Запрос к базе данных
    user = get_object_or_404(User, username=request.user.username)
    all_favorite_authors = user.follower.all() # все любимые авторы пользователя
    post_list = Source_posts(all_favorite_authors) # Написана в отдельном файле utils.py
    #Создание погинатора с параметрами по 10 на странице
    page_obj = My_paginator(request, post_list, NUM_OF_POSTS) # вынесли пагинатор в отдельный файл
    context = {        
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)

@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    Follow.objects.create(
        author_id = author.pk,
        user_id = request.user.pk,
    )
    return redirect('posts:profile', username=username)

@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    delete_follow = Follow.objects.filter(
        author_id=author.pk,
        user_id=request.user.pk,
    )
    delete_follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/post/index.html
{% extends 'base.html' %}
{% block title %}
  <title>{{ title }}</title>
{% endblock %}
{% block content %}
<div class="container py-5">           
  <h1>Последние обновления на сайте</h1>
  <article>
    <ul>
      <li>
        Автор: Лев Толстой
      </li>
      <li>
        Дата публикации: 30 июля 1854
      </li>
    </ul>      
    <p>
      [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
      Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
      Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
      къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
      и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
      ебѣ за нынѣшній день. (3)
    </p>
    <a href="{% url 'post:group_list' %}">все записи группы</a>
  </article>
  <hr>
  <article>
    <ul>
      <li>
        Автор: Лев Толстой
      </li>
      <li>
        Дата публикации: 29 июля 1854
      </li>
    </ul> 
    <p>
      Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
      съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
      что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
      веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
      отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
      — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
      Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
      чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
      накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
      безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
    </p>
    <a href="{% url 'post:group_list' %}">все записи группы</a>
  </article>
  <hr>
  <article>
    <ul>
      <li>
        Автор: Лев Толстой
      </li>
      <li>
        Дата публикации: 28 июля 1854
      </li>
    </ul> 
    <p>
      Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
      Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
      Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
      хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
      Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
      днемъ своимъ очень доволенъ. (1)
    </p>
    <a href="{% url 'post:group_list' %}">все записи группы</a>
  </article>
  <!-- под последним постом нет линии -->
</div>
{% endblock %}